### ISSUE TITLE
Support multi-configuration / matrix projects

### ISSUE THREAD

**Issue by ghost** [jenkinsci/build-time-blame-plugin#11]
I'm attempting to use this plugin with a multi-configuration (a.k.a matrix) projects.

From what I can tell, the report processing happens on the parent job output, which is basically a list of child builds being triggered.

Are there any plans to support matrix projects in the future?

**Comment by LTegtmeier** [comment]
There were not. I haven't used matrix projects. So, I'm not sure how difficult this will be. I'm looking into it.

**Comment by ghost** [comment]
Never mind they are supported - my mistake!

You have to drill down in to a given item on the matrix - in our case we have per-tenant builds of a project and drilling down into the tenant also shows a build time blame report.

For others who might find this, you have to drill down into the matrix item, but *not* a specific build.
