### ISSUE TITLE
Regex match groups in the labels

### ISSUE THREAD

**Issue by Nuxij** [jenkinsci/build-time-blame-plugin#13]
I was wondering if it would be possible to allow the labels to contain results of the regex, probably via matching groups. Something like:

Regex: .*(my_test_[0-9]+)
Label: Start $1

**Comment by LTegtmeier** [comment]
It could do that. A Pull Request would get that option in faster. 😉 The relevant code is in [LogParser.groovy](https://github.com/jenkinsci/build-time-blame-plugin/blob/master/src/main/groovy/org/jenkins/ci/plugins/buildtimeblame/analysis/LogParser.groovy).

But, this plugin is targeted for very broad summaries. If you want to get that kind of granularity, I would recommend a test runner that provides statistics for each test. If you can generate an xUnit report, there is also [a robust Jenkins solution](https://plugins.jenkins.io/xunit). That gives you the option to run tests in parallel and will likely be much more accurate.

**Comment by LTegtmeier** [comment]
I don't think this feature fits in to this plugin. As I noted in the earlier comment, other test runners can give more granular reporting. Jenkins 2.0 pipelines also come with some built in options. See https://github.com/jenkinsci/build-time-blame-plugin/pull/22#issuecomment-649796332.

I don't plan to work on this and don't see any traction.
