### ISSUE TITLE
Files seem to be left open

### ISSUE THREAD

**Issue by dten** [jenkinsci/build-time-blame-plugin#18]
We have a lot of large logs which this takes a significant amount of time for this plugin to process. Annoyingly though after tweaking the regex a few times jenkins will start complaining about a java exception stating too many files open

`lsof | grep jenkins` shows that it has 10s of thousands of log files open. Restarting jenkins makes the error go away

it would appear that logs aren't being closed properly. i had a poke around in this code of this plugin but couldn't see anywhere obvious

**Comment by dten** [comment]
seems like if `closure` ever throws then `inputStream` would not be closed?

https://github.com/jenkinsci/build-time-blame-plugin/blob/18193e87602be69dc02235e2de2c391b69c8c765/src/main/groovy/org/jenkins/ci/plugins/buildtimeblame/io/CustomFileReader.groovy#L11

should this use `withClosable` or something? I have never written any groovy :)
http://docs.groovy-lang.org/latest/html/groovy-jdk/java/io/Closeable.html

**Comment by LTegtmeier** [comment]
Released (belatedly) in [v1.2.1](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/v1.2.1).
