### ISSUE TITLE
Plugins doesn't appear in the job panel

### ISSUE THREAD

**Issue by kriegmaster56** [jenkinsci/build-time-blame-plugin#19]
Hello,
after i installed the plugin version 1.2.0 on a jenkins version 2.176.1 , i doesn't show up in the job panel.
best regards

**Comment by kriegmaster56** [comment]
after further research it appear to only not show up for pipeline jobs.

**Comment by LTegtmeier** [comment]
I've made some progress to make the action show. See #22. I'll take time later to make the report actually work.

**Comment by LTegtmeier** [comment]
🚀 This is released in [v2.0.0](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/v2.0.0). See those notes and the Readme for more details.
