### ISSUE TITLE
Ability to silence "Error finding timestamps" message for older jobs

### ISSUE THREAD

**Issue by HaraldNordgren** [jenkinsci/build-time-blame-plugin#2]
I want the ability to silence the "Error finding timestamps" message on top of the page.

In my organization, we didn't have timestamps enabled until I found this plugin, and so the red warning message now shows up on every project.

Removing the warning could either be done through a settings textbox, "Ignore all jobs before #", to selectively skip all jobs before a certain job number.

Another solution, even easier and possibly better, is a checkbox to simply ignore all jobs without timestamps. This approach seems to work well for the actual graph.

Further analysis might be done to decide which jobs were simply run without timestamps (skip these), and which ones have malformed timestamps (warn about these).

**Comment by LTegtmeier** [comment]
The last solution you gave makes sense, but, unfortunately, the `TimestampReader` we are using from the Timestamper Plugin, only provides `read` methods that give an `Optional` that may or may not contain a timestamp. So, [the code that computes timestamps](https://github.com/jenkinsci/build-time-blame-plugin/blob/master/src/main/groovy/org/jenkins/ci/plugins/buildtimeblame/analysis/LogParser.groovy#L33-L52) does not have a good way to determine if timestamps were not enabled as opposed to failed. 

The "Error finding timestamps" message is intended to tell someone looking at the report (especially the "Mean Successful Build Times" table) that the report is incomplete. 

 I wouldn't want to add a checkbox to ignore all jobs without timestamps. Then, there would be no obvious indication that the report was inaccurate if timestamps stopped working for whatever reason.

Doesn't a textbox setting for "Ignore all jobs before #" just move the existing warning  somewhere else? If there are builds you are going to ignore, then couldn't you just ignore the message? That textbox would allow one user to acknowledge that timestamps are missing for certain builds. But, wouldn't other users also want to know?

I can see making the message less intrusive and/or letting it support ranges (e.g. `Error finding timestamps for builds: 24-78,93`). Would that address this issue?

**Comment by HaraldNordgren** [comment]
I understand about the `TimeStampsReader`. Bummer.

My main problem with the current warning is that there is no way to get rid of it -- barring the removal of old builds. And there is no way to enable timstamps on previous builds, so you are stuck with the warning.

Intervals would be very nice! I would also prefer to drop the red color.

**Comment by LTegtmeier** [comment]
I'm hesitant to permanently hide a warning for a permanent issue with the report. One user could say "I don't care" and ever other user will not know about the issue. 

Does [the PR](https://github.com/jenkinsci/build-time-blame-plugin/pull/4) address this issue? It would only show the warning for builds without timestamps that came after the first build with timestamps.

**Comment by HaraldNordgren** [comment]
I guess the PR would solve the issue for me. :)

**Comment by LTegtmeier** [comment]
Released in: [v1.0.2](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/v1.0.2)
