### ISSUE TITLE
Build Time Blame Report does not open when clicked

### ISSUE THREAD

**Issue by selin194** [jenkinsci/build-time-blame-plugin#23]
I installed this plugin to the Jenkins with version 2.176.3. We have a number of jobs that are configured already. And to see build time blame report for specific jobs I select `Add timestamps to the Console Output`. However, when I clicked the `Build Time Blame Report` from the left of the job, the page is never loads. And it says `Waiting for .....` . What can cause this problem? For this job, other plugins are also used, can be the problem of this? Thank you! @LTegtmeier

**Comment by LTegtmeier** [comment]
I've seen something like this with long or malformed or unexpected console logs or timestamp files.

Can you provide a zip of the Jenkins build directory for a job with this behavior? It should be on the master under `${JENKINS_HOME}/jobs/${JOB_NAME}`.

**Comment by selin194** [comment]
Thank you for responding! Actually, because of the security issues, I am not allowed the shared all of the builds. Do you need console logs of the Jenkins job or other information? I can provide specific logs of the errors that will help us.

**Comment by selin194** [comment]
For example, when I go to the directory `${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${JOB_ID}` I see `buildtimeblamematches` and when I execute 
`cat buildtimeblamematches` I see:

`[{"matchedLine":"Finished: SUCCESS","previousElapsedTime":0,"label":"Finished","timestamp":{"elapsedMillis":607615,"elapsedMillisKnown":true,"millisSinceEpoch":1580888772701}}]`

which means blame is successfully executed, right?

**Comment by selin194** [comment]
Under the directory `${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${JOB_ID}` I see also these files:
 * `build.xml`
* `buildtimeblamematches`
* `changelog.xml`
* `coverage.xml`
* `injectedEnvVars.txt`
* `junitResult.xml`
* `log`
* `sloccount-plugin`
* `timestamper`

Could any of the plugin cause the build time blame report non-clickable?

**Comment by selin194** [comment]
By the way, I already try this `http://${jenkinsHost:8080}/job/${Job-Name}/buildTimeBlameReport/` and page does not open.

**Comment by LTegtmeier** [comment]
> I am not allowed the shared all of the builds. Do you need console logs of the Jenkins job or other information? I can provide specific logs of the errors that will help us.

I would need the `log` and `timestamper` files. Ideally, that would be for all builds in the job with the problem. You could try recreating the problem in a test job without security concerns.

> which means blame is successfully executed, right?

That means that it successfully executed for that build. But, the report would fail to load if **any** builds did not succeed or if there's some other unexpected issue. If sending the relevant files for all builds on the job is not feasible, the builds where you don't see a valid-looking `buildtimeblamematches` file are the most likely causes.

> Could any of the plugin cause the build time blame report non-clickable?

Potentially. The most likely cause is something in the `log` and `timestamper` files. So, we can start there. If I can't reproduce the issue, we can start looking at other plugins.

> I already try this http://${jenkinsHost:8080}/job/${Job-Name}/buildTimeBlameReport/ and page does not open.

The page just spins and never loads anything? Not even an error? The Jenkins Master instance logs may also be printing something in the background. It's been a while since I've had to look one of those up and so I don't remember where they are.

**Comment by selin194** [comment]
I realized something. One of our jobs builds folder contains only `100` jobs build which build time blame report successfully generated. However, for the jobs that build time blame report can not successfully generated have almost `4500` builds!  Could this be the reason of error?

**Comment by selin194** [comment]
Bu the way, I am investigating `log` and `timestamp` files. The timestamp is integrated later, and approximately `100` builds have timestamp and I think that build time blame plugin works well only with these `100` builds.

**Comment by LTegtmeier** [comment]
> However, for the jobs that build time blame report can not successfully generated have almost 4500 builds! Could this be the reason of error?

It could be. The plugin should not be holding on to more memory that it needs. But, it isn't designed to handle huge amounts of data. 

> The timestamp is integrated later, and approximately 100 builds have timestamp and I think that build time blame plugin works well only with these 100 builds.

Yes. The plugin can only do anything if there are timestamps. It should ignore the builds without timestamps without any impact.

**Comment by LTegtmeier** [comment]
The easiest change to the plugin would be to limit the number of builds it will consider. But, making that configurable would be quite a bit of work and if I pick an arbitrary value, it might make the report less valuable on Jenkins Masters that can handle it or for jobs that have short build logs.

**Comment by LTegtmeier** [comment]
🚀 This is released in [v2.0.0](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/v2.0.0). See those notes and the Readme for more details.
