### ISSUE TITLE
Build the project on DEV@cloud and make it show in the Jenkins plugin manager

### ISSUE THREAD

**Issue by HaraldNordgren** [jenkinsci/build-time-blame-plugin#3]
The Build Time Blame Plugin is currently not available in the Jenkins plugin manager.

To start using it, I had to build the code with maven and import the .hpi file. I couldn't find a build status for the project on https://jenkins.ci.cloudbees.com/.

**Comment by LTegtmeier** [comment]
I had trouble publishing earlier. It should be resolved now.
