### ISSUE TITLE
dominantAxis labels elided beyond usability

### ISSUE THREAD

**Issue by krwalker** [jenkinsci/build-time-blame-plugin#34]
Jobs with 4 and 5-digit build numbers and more than 20 data points end up with all of the labels being elided (appear as "...").

This forces us to use <20 data points in order to see the labels.

Could the dominantAxis labels be oriented vertically to allow for more points to appear? Something like `getDomainAxis().setCategoryLabelPositions(CategoryLabelPositions.UP_90);` in BlameReport.groovy?

**Comment by LTegtmeier** [comment]
I think that re-orienting those makes sense. I'll try that out.

By "data points" you mean the number of builds included in the report? And you're controlling that with "Maximum Builds to Process"?

**Comment by krwalker** [comment]
> By "data points" you mean the number of builds included in the report? And you're controlling that with "Maximum Builds to Process"?

Yes. Exactly. And thanks!

**Comment by LTegtmeier** [comment]
#35 fixed this problem by angling the labels. I don't have a machine set up to do the releases. So, I'm still working through getting automatic releases set up. As soon as I can, I will release 2.0.4 with the fix.

**Comment by krwalker** [comment]
Thank you!

**Comment by LTegtmeier** [comment]
The fix was released in [64.vd8f4018a2bbe](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/64.vd8f4018a2bbe) and [2.0.4-65.v671d1c64c6b3](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/2.0.4-65.v671d1c64c6b3).
