### ISSUE TITLE
Error finding timestamps

### ISSUE THREAD

**Issue by NotSoImportant** [jenkinsci/build-time-blame-plugin#36]
Like in #27 I am getting the error message "**Error finding timestamps for builds: 2, 3, 4, 5, 6, 7, 8, 9, 10, 11**"
and graph stays empty

### Steps taken
- builds 1-9 were running without the _timestamper_ plugin enabled was running.
- install _build time blame_ plugin
- enabling the _timestamper_ plugin in the global config
- run build 10
    - times show up under `/job/<jobname>/10/timestamps/?appendLog&elapsed=S`
    - error is shown
    - graph stays empty
- click "Reprocess report"
    - same result 
- restart jenkins
- run build 11
    - same result 

### Comparison of versions
Jenkins version | Timestamper version | Build time blame version | Timestamp output | Result
--- | --- | --- | --- | ---
2.204.1 | 1.10 | 64.vd8f4018a2bbe | `[2021-11-18T13:48:47.534Z] Started by user <username>` | "Error finding timestamps", no data
2.303.1 | 1.13 | 64.vd8f4018a2bbe | `12  Started by user <username>` | No error, no data

**Comment by NotSoImportant** [comment]
Found actually I was only triggering failing builds in the 2.303.1 jenkins instance and once having a passing one it was successful, so closing this issue.

**Comment by NotSoImportant** [comment]
@LTegtmeier I have a question: in the readme it states that "This plugin scans console output for successful builds", but the regex for the build end is `^Finished: (SUCCESS|UNSTABLE|FAILURE|NOT_BUILT|ABORTED)$.*`
I only see metrics from passing (SUCCESSful) builds. Is this expected?
![image](https://user-images.githubusercontent.com/35758921/142618677-02955011-df4d-4bd5-a209-22c853755ff0.png)
Build 8 is missing, because it was failing, but actually was much longer running.
Build output `/job/<jobname>/8/timestamps/?appendLog&elapsed=S` ends with:
```
5107215  [Pipeline] End of Pipeline
5107356  Finished: FAILURE
```
![image](https://user-images.githubusercontent.com/35758921/142618772-55c26be8-e2d6-4ec8-a5a1-1a294a096b25.png)

**Comment by LTegtmeier** [comment]
> I only see metrics from passing (SUCCESSful) builds. Is this expected?

This is intentional. This plugin only includes successful builds because it assumes that they are the norm and the thing you are trying to optimize. A failed build may take far longer than usual (like in your example) or way less time than usual (for example, a compile error). The graph from this plugin really only works if you have a consistent set of steps from build to build which is much easier to manage.

> the regex for the build end is ^Finished: (SUCCESS|UNSTABLE|FAILURE|NOT_BUILT|ABORTED)$.*

This regex is set to be a bit more future-proof. The intent is to match the final line of any Jenkins build regardless of status. It doesn't "know" about the success-only filtering rule.

**Comment by NotSoImportant** [comment]
> This is intentional. This plugin only includes successful builds 
> [...]
> The graph from this plugin really only works if you have a consistent set of steps from build to build which is much easier to manage.

Is there any way to enable it also for failing builds if I want to? Of course the graph could potentially not have all stages then. Is that the problem, that the plot cannot deal with this right now?

**Comment by LTegtmeier** [comment]
I really should have said that the tables and/or graph could be misleading with failed builds or missing steps in them. Functionally, they would work with limited data. But, they wouldn't accurately point you to which steps are slowing you down and should be targeted for optimization. 

I usually treat failed builds as a separate problem where the only goal is to make it turn green and the performance doesn't matter. 

> Is there any way to enable it also for failing builds if I want to?

If you'd like to file a separate issue to add that feature, I think it is a reasonable option for the report for teams that are okay with the build-to-build discrepancy.
