### ISSUE TITLE
Feature: Ability to record parallel runs

### ISSUE THREAD

**Issue by NotSoImportant** [jenkinsci/build-time-blame-plugin#37]
This plugin is very helpful. However it seem to be only able to record one step after each other. Calculation of parallel executions would be terminated by each other.

Could this be achived by e.g. optionally providing not only a start pattern, but also an end-pattern per matching entry?

**Comment by LTegtmeier** [comment]
Thanks for your interest and feedback on this plugin!

This is more of a general comment that I think relates to all of the issues you filed.

For some background, this plugin was made before I had ever used Jenkins2.0 pipelines. We had a plain Freestyle Jenkins Job with a fairly long, sequential build with somewhat erratic timing. It also used multiple build tools embedded in maven. So, it was hard to add instrumentation to each step. This plugin helps to solve that problem but, Jenkins2.0 pipelines give you other options to quickly see how long each build step takes. 

In principle, this plugin could be enhanced or rewritten to cover more scenarios. To be honest, I haven't used Jenkins heavily in quite a while and I haven't had much need for a graph like this plugin produces. Small patches and re-releases for this plugin are easy and I'm happy to maintain it but, making it truly Jenkins2.0-native or adding advanced features is hard for me to justify.

**Comment by LTegtmeier** [comment]
> Calculation of parallel executions would be terminated by each other.

Are these parallel executions different stages in a Jenkins2.0 pipeline build? If so, can you rely on the build times reported on each stage?

That won't automatically aggregate across builds but, it may be an easier path to the metrics you want. You may need to break your stages into smaller commands to get better insights.

> Could this be achived by e.g. optionally providing not only a start pattern, but also an end-pattern per matching entry?

Start and end patterns for each parallel execution or enhancing the plugin to support gathering metrics at the stage level would help you see how long each parallel step took but, it would not directly help you "blame" your build time on one step or another. 

If I were relying on this plugin as-is to diagnose build times for a job with parallel steps, I would set labels for before and after the set of parallel steps. Then I would know whether that block as a whole should be optimized and I would look at individual builds or temporarily turn off the parallelism to better diagnose where the time is going and what I could optimize.

For example, consider you have a job like this where any steps with the same "Order" run in parallel:
| Step | Order | Time |
|------|--------|-------|
|  Clone | 1 | 5 seconds |
| Pull Dependencies | 2 | 5 minutes |
| Lint | 3 | 5 minutes |
| Unit Test | 3 | 11 minutes |
| Package | 3 | 10 minutes |
| Deploy | 5 | 1 minutes | 

From that, you might decide that Packaging is a long-running step but, any optimization there won't actually reduce your build time. Similarly, reducing unit test time can remove at most 1 minute from the build time. You might get the best impact by adding a dependency cache even though that is a relatively fast step.
