### ISSUE TITLE
Plugin icon not displayed

### ISSUE THREAD

**Issue by lisageorgy21** [jenkinsci/build-time-blame-plugin#51]
**Description**
The plugin icon on the left side of Jenkins job page is improperly displayed as shown below (tested in Jenkins versions, 2.362 and 2.375.1).
![image](https://user-images.githubusercontent.com/110609020/205686243-6929edb0-e9ad-4725-870f-d17101a1c06e.png)

The icon is clearly shown in Jenkins version 1.656.
![image](https://user-images.githubusercontent.com/110609020/205686732-8f5b43c3-fdfb-47be-b9a3-6d32f70b0188.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/110609020/205687790-21329fcb-fe79-4867-8424-b8e86ce10bce.png)

**Comment by danaltemyr** [comment]
I see the same problem. As far as can understand, the missing icon is referred to as <JENKINS_URL>/static/b880517a/images/24x24/monitor.png, and all .png files have been removed from jenkins core and are replaced by svg graphics a while ago.

**Comment by LTegtmeier** [comment]
Thanks for investigating this! I'll take some time to update everything to be in line with the latest Jenkins core.

**Comment by LTegtmeier** [comment]
I closed this with the release for #54. But, it was actually fixed by #40. You were just stuck with the old version because of https://github.com/jenkinsci/build-time-blame-plugin/issues/49.

You should get a working version by installing v70 or v2.0.4.
