### ISSUE TITLE
Feature: Graph Tooltips and Job Links

### ISSUE THREAD

**Issue by rcowsill** [jenkinsci/build-time-blame-plugin#57]
The standard Jenkins "Build Time Trend" graph has a couple of features which make it easier to use. Hovering over the graph shows a tooltip with the build number and duration for the run under the pointer. Also, the part of the graph representing a particular run is a link to that run's page. This makes it easy to get the exact run duration, and jump to the details of an unusually slow/fast run.

Since this plugin uses the same chart library as the "Build Time Trend", it's possible to add those features here. I'm happy to make a PR with the changes if that sounds useful.

Here's a screenshot of a prototype version:

![graph](https://github.com/jenkinsci/build-time-blame-plugin/assets/42620235/05a86a47-7d76-40ba-a4da-97e02c255b38)

**Comment by LTegtmeier** [comment]
That sounds like a good new feature! 

I'd be happy to review a PR for it. If I remember correctly, the unit tests don't care about the formatting, only the data. So, it should be pretty straightforward. It's probably also worth updating [the example image](https://github.com/jenkinsci/build-time-blame-plugin/blob/master/documentation/images/build_time_trend.png) to include the hover effect.

**Comment by LTegtmeier** [comment]
This was released as [`73.vf11a_807a_94b_5-2.1.0`](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/73.vf11a_807a_94b_5-2.1.0).

Thanks for the help, @rcowsill!
